namespace PwDemo.Scripts;

/// <summary>
/// JavaScript snippets executed inside the page via Playwright.
/// </summary>
public static class JsScripts
{
    /// <summary>
    /// Extracts a list of visible/interactive elements from the document.
    /// For each element, returns a stable selector that prefers (in order):
    ///   1. #id (when id looks stable, i.e. not auto-generated)
    ///   2. [data-testid=...] / [data-test=...] / [data-qa=...]
    ///   3. [name=...], [aria-label=...], [role=...] combined with tag
    ///   4. text-based selector for buttons/links
    ///   5. CSS path using tag + :nth-of-type() as a deterministic fallback
    /// Dynamic / auto-generated class names (e.g. CSS-modules hashes) are
    /// intentionally ignored so selectors stay stable across builds.
    /// </summary>
    public const string ExtractElements = @"
(() => {
    const INTERACTIVE = new Set([
        'A','BUTTON','INPUT','SELECT','TEXTAREA','LABEL','OPTION','SUMMARY'
    ]);

    const looksAutoGeneratedId = (v) => {
        if (!v) return true;
        if (v.length > 40) return true;
        if (/^[a-z]+-[a-f0-9]{6,}$/i.test(v)) return true;
        if (/^[a-f0-9]{8,}$/i.test(v)) return true;
        if (/^:r[0-9a-z]+:$/i.test(v)) return true; // React useId
        if (/^ember\d+$/i.test(v)) return true;
        if (/^mui-\d+$/i.test(v)) return true;
        return false;
    };

    const looksAutoGeneratedClass = (c) => {
        if (!c) return true;
        if (/[_-][a-z0-9]{5,}$/i.test(c) && /\d/.test(c)) return true;
        if (/^css-[a-z0-9]{4,}$/i.test(c)) return true;
        if (/^jsx-\d+/i.test(c)) return true;
        if (/^sc-[a-z0-9]+/i.test(c)) return true;
        if (/^[a-z0-9]{8,}$/i.test(c) && /\d/.test(c) && /[a-z]/i.test(c)) return true;
        return false;
    };

    const cssEscape = (s) => (window.CSS && CSS.escape) ? CSS.escape(s) : String(s).replace(/([^a-zA-Z0-9_-])/g, '\\$1');

    const attrSelector = (el, name) => {
        const v = el.getAttribute(name);
        if (v === null || v === '') return null;
        return `[${name}=""${v.replace(/""/g, '\\""')}""]`;
    };

    const isUnique = (sel, root = document) => {
        try { return root.querySelectorAll(sel).length === 1; } catch { return false; }
    };

    const stableClassPart = (el) => {
        const classes = (el.getAttribute('class') || '')
            .split(/\s+/)
            .filter(c => c && !looksAutoGeneratedClass(c));
        if (classes.length === 0) return '';
        return classes.slice(0, 2).map(c => '.' + cssEscape(c)).join('');
    };

    const cssPath = (el) => {
        const parts = [];
        let node = el;
        while (node && node.nodeType === 1 && node !== document.documentElement) {
            let part = node.tagName.toLowerCase();
            const parent = node.parentElement;
            if (parent) {
                const sameTag = Array.from(parent.children).filter(c => c.tagName === node.tagName);
                if (sameTag.length > 1) {
                    const idx = sameTag.indexOf(node) + 1;
                    part += `:nth-of-type(${idx})`;
                }
            }
            parts.unshift(part);
            node = parent;
            if (parts.length >= 6) break;
        }
        return parts.join(' > ');
    };

    const buildSelector = (el) => {
        const id = el.id;
        if (id && !looksAutoGeneratedId(id)) {
            const sel = '#' + cssEscape(id);
            if (isUnique(sel)) return sel;
        }

        for (const a of ['data-testid','data-test','data-qa','data-cy']) {
            const s = attrSelector(el, a);
            if (s && isUnique(s)) return s;
        }

        const tag = el.tagName.toLowerCase();

        for (const a of ['name','aria-label','aria-labelledby','role','placeholder','title']) {
            const s = attrSelector(el, a);
            if (s) {
                const sel = tag + s;
                if (isUnique(sel)) return sel;
            }
        }

        if ((tag === 'button' || tag === 'a') && el.innerText) {
            const text = el.innerText.trim().slice(0, 40);
            if (text) {
                return `${tag}:has-text(""${text.replace(/""/g, '\\""')}"")`;
            }
        }

        const classPart = stableClassPart(el);
        if (classPart) {
            const sel = tag + classPart;
            if (isUnique(sel)) return sel;
        }

        return cssPath(el);
    };

    const isVisible = (el) => {
        const r = el.getBoundingClientRect();
        if (r.width === 0 && r.height === 0) return false;
        const style = getComputedStyle(el);
        if (style.visibility === 'hidden' || style.display === 'none') return false;
        return true;
    };

    const results = [];
    const all = document.querySelectorAll('*');
    for (const el of all) {
        const tag = el.tagName;
        const role = el.getAttribute('role');
        const interactive = INTERACTIVE.has(tag) || role !== null || el.hasAttribute('onclick');
        if (!interactive) continue;
        if (!isVisible(el)) continue;

        results.push({
            tag: tag.toLowerCase(),
            text: (el.innerText || '').trim().slice(0, 120),
            id: el.id || null,
            name: el.getAttribute('name') || null,
            type: el.getAttribute('type') || null,
            role: role || null,
            ariaLabel: el.getAttribute('aria-label') || null,
            placeholder: el.getAttribute('placeholder') || null,
            href: el.getAttribute('href') || null,
            value: (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT') ? (el.value ?? null) : null,
            selector: buildSelector(el)
        });
    }
    return results;
})()
";

    /// <summary>
    /// Produces a simplified HTML representation of the current document.
    /// Strips script/style/svg/link/meta, comments, inline event handlers,
    /// style, class, and most non-semantic attributes, preserving only
    /// attributes useful for automation.
    /// </summary>
    public const string SimplifyHtml = @"
(() => {
    const KEEP_ATTRS = new Set([
        'id','name','type','role','href','src','alt','title','value',
        'placeholder','aria-label','aria-labelledby','aria-describedby',
        'data-testid','data-test','data-qa','data-cy','for','action','method'
    ]);
    const DROP_TAGS = new Set(['SCRIPT','STYLE','NOSCRIPT','SVG','LINK','META']);

    const clone = document.documentElement.cloneNode(true);

    clone.querySelectorAll('*').forEach(el => {
        if (DROP_TAGS.has(el.tagName)) {
            el.remove();
            return;
        }
    });

    const walker = document.createTreeWalker(clone, NodeFilter.SHOW_COMMENT, null);
    const toRemove = [];
    let n;
    while ((n = walker.nextNode())) toRemove.push(n);
    toRemove.forEach(c => c.parentNode && c.parentNode.removeChild(c));

    clone.querySelectorAll('*').forEach(el => {
        for (const attr of Array.from(el.attributes)) {
            const name = attr.name.toLowerCase();
            if (name.startsWith('on')) { el.removeAttribute(attr.name); continue; }
            if (name === 'style' || name === 'class') { el.removeAttribute(attr.name); continue; }
            if (!KEEP_ATTRS.has(name) && !name.startsWith('data-')) {
                el.removeAttribute(attr.name);
            }
        }
    });

    const textWalker = document.createTreeWalker(clone, NodeFilter.SHOW_TEXT, null);
    const texts = [];
    let t;
    while ((t = textWalker.nextNode())) texts.push(t);
    texts.forEach(tn => { tn.nodeValue = tn.nodeValue.replace(/\s+/g, ' '); });

    return '<html>' + clone.innerHTML + '</html>';
})()
";
}
